repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: mixed-line-ending
        args: ["--fix=no"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v3.10.1'
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]
  - repo: https://github.com/psf/black
    rev: '23.7.0'
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
        additional_dependencies: [".[toml]"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.0'
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--install-types", "--non-interactive"]
        additional_dependencies:
          - calmjs.parse==1.3.0  # optional
          - cheroot==8.6.0
          - flask==2.3.2
          - genutility[file,json,pickle,rich,time]==0.0.102
          - humanize==4.7.0
          - jsonschema==4.19.0
          - MarkupSafe==2.1.3
          - pathspec==0.11.2
          - platformdirs==3.10.0
          - Pygments==2.16.1  # optional
          - Pympler==1.0.1
          - rich==13.5.2
          - spacy==3.6.0
