repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.2.0'
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: mixed-line-ending
        args: ["--fix=no"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.32.0'
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]
  - repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--install-types", "--non-interactive"]
        additional_dependencies:
          - appdirs==1.4.4
          - calmjs.parse==1.3.0  # optional
          - cheroot==8.5.2
          - flask==2.0.2
          - genutility[json]==0.0.78
          - humanize==3.12.0
          - jsonschema==4.2.1
          - MarkupSafe==2.0.1
          - pathspec==0.9.0
          - Pygments==2.10.0  # optional
          - Pympler==0.9
          - spacy==3.2.0
          - tqdm==4.62.3
