[tool.black]
line-length = 120

[tool.isort]
profile = "black"
src_paths = ["."]
line_length = 120

[tool.bandit]
skips = ["B101"]

[tool.poetry]
name = "desktop-search"
version = "0.1.0"
description = "Full text search for code and text files"
authors = ["Dobatymo <Dobatymo@users.noreply.github.com>"]
license = "ISC license"

[tool.poetry.scripts]
app = "wsgi:main"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.3.2"
MarkupSafe = "^2.1.1"
platformdirs = "^3.5.0"
"calmjs.parse" = "^1.3.0"
cheroot = "^8.6.0"
humanize = "^4.0.0"
jsonschema = "^4.4.0"
pathspec = "^0.11.1"
Pygments = "^2.11.2"
spacy = "^3.5.2"
tqdm = "^4.64.0"
genutility = {extras = ["json"], version = "^0.0.99"}
Pympler = "^1.0.1"
Whoosh = "^2.7.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
