[tool.isort]
profile = "black"
src_paths = ["."]
line_length = 120
known_thirdpartyfuture = ["builtins", "future", "past"]
sections = ["FUTURE", "THIRDPARTYFUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
