name: Python package

on: [push]

jobs:

  lint:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -U pip wheel
        python -m pip install ruff bandit[toml]
    - run: python -m ruff check
    - run: python -m ruff format
    - run: python -m bandit . --recursive -c pyproject.toml

  test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: python -m pip install -U uv
    - name: Run tests
      run: python -m uv run --group test -m pytest
