name: Python package

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -U pip wheel
        python -m pip install black isort flake8 bandit[toml]
    - run: python -m black . --check
    - run: python -m isort . --check-only
    - run: python -m flake8 .
    - run: python -m bandit . --recursive -c pyproject.toml

  test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install -U pip wheel poetry
        python -m poetry config virtualenvs.create false
        python -m poetry install --no-root
        python -m spacy download en_core_web_sm
    - name: Run tests
      run: |
        python -OO -m unittest discover -v -s tests
